namespace RiseFlow.Api.Models;

public record CreateTeacherRequest(
    string FirstName,
    string LastName,
    string? MiddleName,
    string? Email,
    string? Phone,
    string? WhatsAppNumber,
    string? StaffId,
    string? SubjectSpecialization,
    DateOnly? DateOfBirth,
    string? Gender,
    string? Nationality,
    string? StateOfOrigin,
    string? LGA,
    string? NIN,
    string? NationalIdType,
    string? NationalIdNumber,
    string? TrcnNumber,
    string? ResidentialAddress,
    string? HighestQualification,
    string? FieldOfStudy,
    int? YearsOfExperience,
    string? PreviousSchools,
    string? ProfessionalBodies,
    DateOnly? DateEmployed,
    string? EmploymentType,
    string? RoleTitle,
    string? Department,
    decimal? BaseSalaryAmount,
    string? BaseSalaryCurrency,
    string? AllowancesNote,
    string? PromotionHistory,
    string? Recognitions);

public record UpdateTeacherRequest(
    string FirstName,
    string LastName,
    string? MiddleName,
    string? Email,
    string? Phone,
    string? WhatsAppNumber,
    string? StaffId,
    string? SubjectSpecialization,
    DateOnly? DateOfBirth,
    string? Gender,
    string? Nationality,
    string? StateOfOrigin,
    string? LGA,
    string? NIN,
    string? NationalIdType,
    string? NationalIdNumber,
    string? TrcnNumber,
    string? ResidentialAddress,
    string? HighestQualification,
    string? FieldOfStudy,
    int? YearsOfExperience,
    string? PreviousSchools,
    string? ProfessionalBodies,
    DateOnly? DateEmployed,
    string? EmploymentType,
    string? RoleTitle,
    string? Department,
    decimal? BaseSalaryAmount,
    string? BaseSalaryCurrency,
    string? AllowancesNote,
    string? PromotionHistory,
    string? Recognitions,
    bool IsActive);

public record AssignTeacherToClassRequest(string? RoleInClass);

public record TeacherSignupRequest(
    Guid SchoolId,
    string Email,
    string Password,
    string FirstName,
    string LastName,
    string? MiddleName,
    string? Phone,
    string? WhatsAppNumber,
    string? StaffId,
    DateOnly? DateOfBirth,
    string? Gender,
    string? Nationality,
    string? StateOfOrigin,
    string? LGA,
    string? NIN,
    string? NationalIdType,
    string? NationalIdNumber,
    string? TrcnNumber,
    string? ResidentialAddress,
    string? HighestQualification,
    string? FieldOfStudy,
    int? YearsOfExperience,
    string? PreviousSchools,
    string? ProfessionalBodies);

public record TeacherSignupResult(bool Success, string Message);
