namespace RiseFlow.Api.Models;

public record CreateTeacherRequest(
    string FirstName,
    string LastName,
    string? MiddleName,
    string? Email,
    string? Phone,
    string? WhatsAppNumber,
    string? StaffId,
    string? SubjectSpecialization,
    DateOnly? DateOfBirth,
    string? Gender,
    string? Nationality,
    string? StateOfOrigin,
    string? LGA,
    string? Religion,
    string? NIN,
    string? NationalIdType,
    string? NationalIdNumber,
    string? TrcnNumber,
    string? ResidentialAddress,
    string? HighestQualification,
    string? FieldOfStudy,
    int? YearsOfExperience,
    string? PreviousSchools,
    string? ProfessionalBodies,
    DateOnly? DateEmployed,
    string? EmploymentType,
    string? RoleTitle,
    string? Department,
    decimal? BaseSalaryAmount,
    string? BaseSalaryCurrency,
    string? AllowancesNote,
    string? PromotionHistory,
    string? Recognitions);

public record UpdateTeacherRequest(
    string FirstName,
    string LastName,
    string? MiddleName,
    string? Email,
    string? Phone,
    string? WhatsAppNumber,
    string? StaffId,
    string? SubjectSpecialization,
    DateOnly? DateOfBirth,
    string? Gender,
    string? Nationality,
    string? StateOfOrigin,
    string? LGA,
    string? Religion,
    string? NIN,
    string? NationalIdType,
    string? NationalIdNumber,
    string? TrcnNumber,
    string? ResidentialAddress,
    string? HighestQualification,
    string? FieldOfStudy,
    int? YearsOfExperience,
    string? PreviousSchools,
    string? ProfessionalBodies,
    DateOnly? DateEmployed,
    string? EmploymentType,
    string? RoleTitle,
    string? Department,
    decimal? BaseSalaryAmount,
    string? BaseSalaryCurrency,
    string? AllowancesNote,
    string? PromotionHistory,
    string? Recognitions,
    bool IsActive,
    IReadOnlyList<TeacherProfileFieldSettingUpdateDto>? FieldSettings,
    IReadOnlyList<TeacherCustomFieldInputDto>? CustomFields);

public record UpdateMyTeacherProfileRequest(
    string FirstName,
    string LastName,
    string? MiddleName,
    string? Phone,
    string? WhatsAppNumber,
    string? StaffId,
    string? SubjectSpecialization,
    DateOnly? DateOfBirth,
    string? Gender,
    string? Nationality,
    string? StateOfOrigin,
    string? LGA,
    string? Religion,
    string? NIN,
    string? NationalIdType,
    string? NationalIdNumber,
    string? TrcnNumber,
    string? ResidentialAddress,
    string? HighestQualification,
    string? FieldOfStudy,
    int? YearsOfExperience,
    string? PreviousSchools,
    string? ProfessionalBodies,
    IReadOnlyList<TeacherCustomFieldInputDto>? CustomFields);

public record AssignTeacherToClassRequest(string? RoleInClass);

public record TeacherSignupRequest(
    Guid SchoolId,
    string Email,
    string Password,
    string FirstName,
    string LastName,
    string? MiddleName,
    string? Phone,
    string? WhatsAppNumber,
    string? StaffId,
    DateOnly? DateOfBirth,
    string? Gender,
    string? Nationality,
    string? StateOfOrigin,
    string? LGA,
    string? Religion,
    string? NIN,
    string? NationalIdType,
    string? NationalIdNumber,
    string? TrcnNumber,
    string? ResidentialAddress,
    string? HighestQualification,
    string? FieldOfStudy,
    int? YearsOfExperience,
    string? PreviousSchools,
    string? ProfessionalBodies);

public record TeacherSignupResult(bool Success, string Message);

public record TeacherProfileFieldSettingDto(
    string FieldKey,
    string DisplayName,
    bool IsCustom,
    bool IsVisibleToTeacher,
    bool IsEditableByTeacher,
    bool IsAdminOnly,
    int SortOrder);

public record TeacherProfileFieldSettingUpdateDto(
    string FieldKey,
    string DisplayName,
    bool IsCustom,
    bool IsVisibleToTeacher,
    bool IsEditableByTeacher,
    bool IsAdminOnly,
    int SortOrder);

public record TeacherCustomFieldDto(
    string FieldKey,
    string DisplayName,
    string? Value,
    bool IsVisibleToTeacher,
    bool IsEditableByTeacher,
    bool IsAdminOnly,
    int SortOrder);

public record TeacherCustomFieldInputDto(
    string FieldKey,
    string? DisplayName,
    string? Value,
    bool IsVisibleToTeacher = true,
    bool IsEditableByTeacher = true,
    bool IsAdminOnly = false,
    int SortOrder = 0);

public record TeacherAssignedClassDto(Guid ClassId, string ClassName, string? AcademicYear, string? RoleInClass);

public record TeacherProfileDto(
    Guid Id,
    Guid SchoolId,
    string FirstName,
    string LastName,
    string? MiddleName,
    string? Email,
    string? Phone,
    string? WhatsAppNumber,
    string? StaffId,
    string? SubjectSpecialization,
    DateOnly? DateOfBirth,
    string? Gender,
    string? Nationality,
    string? StateOfOrigin,
    string? LGA,
    string? Religion,
    string? NIN,
    string? NationalIdType,
    string? NationalIdNumber,
    string? TrcnNumber,
    string? ResidentialAddress,
    string? HighestQualification,
    string? FieldOfStudy,
    int? YearsOfExperience,
    string? PreviousSchools,
    string? ProfessionalBodies,
    DateOnly? DateEmployed,
    string? EmploymentType,
    string? RoleTitle,
    string? Department,
    decimal? BaseSalaryAmount,
    string? BaseSalaryCurrency,
    string? AllowancesNote,
    string? PromotionHistory,
    string? Recognitions,
    string? ProfilePhotoFileName,
    bool IsActive,
    int AssignedClassCount,
    int AssignedStudentCount,
    DateTime CreatedAtUtc,
    DateTime? UpdatedAtUtc,
    IReadOnlyList<TeacherAssignedClassDto> TeacherClasses,
    IReadOnlyList<TeacherProfileFieldSettingDto> FieldSettings,
    IReadOnlyList<TeacherCustomFieldDto> CustomFields);
